version: 0.2

phases:
  pre_build:
    commands:
      - apt-get install -y nodejs
      - npm install
      - npm install forever -g
      - forever start app.js
  build:
    commands:
      - sudo npm test
  post_build:
    commands:
      - forever stopall
artifacts:
  files:
    - '**/*'
