version: 0.2
# env:
#   variables:
#     NODE_VERSION: "11"

phases:
  # install:
  #   runtime-versions:
  #     nodejs: $NODE_VERSION
  pre_build:
    commands:
      # - apt-get install curl -y
      # - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x > script.sh
      # - bash script.sh
      # - apt-get install -y nodejs
      - npm install
      - npm install forever -g
      - npm install chai -g
      - npm install mocha -g
      - forever start app.js
  build:
    commands:
      - npm test
  post_build:
    commands:
      - forever stopall
artifacts:
  files:
    - '**/*'
