version: 0.2
env:
  variables:
    NODE_VERSION: "13.9.0"

phases:
  pre_build:
    commands:
      - apt-get install curl -y
      - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x > script.sh
      - bash script.sh
      - apt-get install -y nodejs
      - npm install
      - npm install forever -g
      - forever start app.js
      # - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      # - export NVM_DIR="$HOME/.nvm"
      # - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      # - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      # # - export NVM_DIR="$HOME/.nvm" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      # - nvm install $NODE_VERSION
      # # - apt-get install curl -y
      # # - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x > script.sh
      # # - bash script.sh
      # # - apt-get install -y nodejs
      # - npm install
      # - npm install forever -g
      # - forever start app.js
  build:
    commands:
      - npm test
  post_build:
    commands:
      - forever stopall
artifacts:
  files:
    - '**/*'
