version: 0.2
# env:
#   variables:
#     NODE_VERSION: "10" 

phases:
  # install:
  #   runtime-versions:
  #     nodejs: $NODE_VERSION #used with AWS managed docker images (standard 3.0)
  pre_build:
    commands:
      - npm install
      - npm install forever -g
      - forever start app.js
  build:
    commands:
      - npm test
  post_build:
    commands:
      - forever stopall
artifacts:
  files:
    - '**/*'
