version: 0.2
env:
  variables:
    NODE_VERSION: "12"

phases:
  install:
    runtime-versions:
      nodejs: $NODE_VERSION
  pre_build:
    commands:
      - npm install forever -g
      - forever start app.js
  build:
    commands:
      - npm test
  post_build:
    commands:
      - forever stopall
# artifacts:
#   files:
#     - '**/*'
