version: 0.2
env:
  variables:
    NODE_VERSION: "11"

phases:
  # install:
  #   runtime-versions:
  #     nodejs: $NODE_VERSION
  pre_build:
    commands:
      - forever start app.js
  build:
    commands:
      - npm test
  post_build:
    commands:
      - forever stopall
artifacts:
  files:
    - '**/*'
