version: 0.2

phases:
  pre_build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install
      - npm isntall forever -g
      - forever start app.js
  build:
    commands:
      - npm test
  post_build:
    commands:
      - forever stopall
artifacts:
  files:
    - 'test/*'
    - 'app.js'
    - 'package.json'
    - 'buildspec.yml'
    - 'appspec.yml'
